### PR TITLE
Ruby 3.3 support (version 0.8.0)

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
@josacar  I am struggling with Ruby 3.3 support on Windows but we will be happy to publish a pre release version of this gem with Linux/Mac support if you kindly do beta test :)
Thank you

**Comment by josacar** [comment]
@maxirmx I can give it a try with some apps if you want, I don't have an urgent rush but I'm happy to see ongoing maintenance on Ruby packers.

I tested the latest version and in Linux works very nice, in osx it is slower when invoking the executable. 

Thanks for your work!

**Comment by maxirmx** [comment]
> @maxirmx I can give it a try with some apps if you want, I don't have an urgent rush but I'm happy to see ongoing maintenance on Ruby packers.
> 
> I tested the latest version and in Linux works very nice, in osx it is slower when invoking the executable.
> 
> Thanks for your work!

Thank you, I thought you were waiting for it. 
We will be able to release 3.3 support in a couple of days.

If you can share details about your observation that osx is slower I will appreciate.
Thank you

**Comment by josacar** [comment]
> > @maxirmx I can give it a try with some apps if you want, I don't have an urgent rush but I'm happy to see ongoing maintenance on Ruby packers.
> > 
> > I tested the latest version and in Linux works very nice, in osx it is slower when invoking the executable.
> > 
> > Thanks for your work!
> 
> Thank you, I thought you were waiting for it. 
> We will be able to release 3.3 support in a couple of days.
> 
> If you can share details about your observation that osx is slower I will appreciate.
> Thank you

Do you want to create an issue for this or how do you want me to share it with you ?

**Comment by maxirmx** [comment]
> > > @maxirmx I can give it a try with some apps if you want, I don't have an urgent rush but I'm happy to see ongoing maintenance on Ruby packers.
> > > I tested the latest version and in Linux works very nice, in osx it is slower when invoking the executable.
> > > Thanks for your work!
> > 
> > 
> > Thank you, I thought you were waiting for it.
> > We will be able to release 3.3 support in a couple of days.
> > If you can share details about your observation that osx is slower I will appreciate.
> > Thank you
> 
> Do you want to create an issue for this or how do you want me to share it with you ?

Please create an issue

**Pull request merged**
