### PR TITLE
feat: an option to remove GLIBC_PRIVATE reference on Linux Gnu

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
This feature will allow to run packages pressed with Ubuntu 20 in other linux gnu environments

**Comment by ronaldtse** [comment]
@maxirmx time for a blog post? 😉

**Comment by maxirmx** [comment]
> @maxirmx time for a blog post? 😉

I plan to create a workflow that runs on Rocky Linux, creates tebako package using Ubuntu container and then runs the package on native Rocky Linux

Then I will describe it in README and blog post as generic approach for gnu linux systems. ok ?

**Comment by ronaldtse** [comment]
That's perfect. Thanks @maxirmx !

**Pull request merged**
