### PR TITLE
fix: allow use setup-tebako from other repos

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP how about we make a new "setup-tebako" repo just like the Fontist one?

**Review by maxirmx — COMMENTED** [review]
LGTM, but MacOS runners are in a bad shape again
I will merge it later and will bunp tebako version

**Comment by CAMOBAP** [comment]
@ronaldtse To me it seems that due to maintainability (common.env duplication), it's better to keep `setup-tebako` in the `tebako` repo

@maxirmx how od you think?

**Comment by maxirmx** [comment]
@CAMOBAP I guess. I can get rid of common.env.
I have another possible issue in mind - setup-tebako will depend on tebako, so if tebako workflow uses setup-tebako action it will create a circular dependency that will be hard to maintain.

Let's keep it in the same repo for now. I suggest will look at the options to simplify setup first.

**Pull request merged**
