### PR TITLE
Version 0.7.2

### PR DESCRIPTION
**Pull request by maxirmx**
It was seen as a small bug fix but grew to a major rework ...

### CODE REVIEW

**Comment by ronaldtse** [comment]
Please add `--devmode` description to README, thanks.

**Comment by maxirmx** [comment]
It was seen as a small bug fix but grew to a major rework ...

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx ! We will definitely need to update the readme on how to rebuild the tebako user environment with clean and setup etc.

**Comment by ronaldtse** [comment]
Let's release a new version. Thanks!

**Pull request merged**
