### PR TITLE
Created tebako as a Ruby gem

### PR DESCRIPTION
**Pull request by maxirmx**

### CODE REVIEW

**Comment by maxirmx** [comment]
@ronaldtse 
Could you please create TEBAKO_CI_RUBYGEMS_API_KEY token  so that tebako can be published ?
Thank you

**Review by ronaldtse — APPROVED** [review]
Thank you @maxirmx !

**Comment by ronaldtse** [comment]
@maxirmx the ubuntu-aarch64 job is failing... can we fix this before merging? Thanks.

**Comment by maxirmx** [comment]
Rubygems site is unstable today. We can wait

```Fetching source index from https://rubygems.org/
Network error while fetching
https://rubygems.org/quick/Marshal.4.8/ffi-0.1.0.gemspec.rz (Connection reset by
peer - SSL_connect)
```

**Comment by ronaldtse** [comment]
Screenshot 2023-06-16 at 12 12 17 PM

@maxirmx created Rubygems API key.

**Pull request merged**
