### PR TITLE
fix: provide LG_VADDR option for jemalloc build on MacOS

### PR DESCRIPTION
**Pull request by maxirmx**
This PR adresses #177 

**Background**
- We have to use jemalloc, otherwise big packages like metanorma suffer significant performance degradation.
- On MacOS we have to create pristine installation of jemalloc that has static library only. This is required because of limitations of apple linker that lacks options to prefer static library and not dynamic library if both are present and the 'magic' that folly uses for linking.
- jemalloc build script fails to detect emulated environment. There are known issues related to Rosetta (https://github.com/jemalloc/jemalloc/issues/1997), it looks like QEMU emulation has similar problems
- theoretically we can automate selection of correct parameter but practically it will require testing that will exceed our capabilities

**Proposed and implemented solution**
- provide support of environment variable to set correct jemalloc build parameter(s) on MacOS if emulation is used
For example, if it is arm64 emulated on QEMU just use
```
export LG_VADDR=39
```

if it is x86_64 emulated with Rosetta use
```
export LG_VADDR=48
```

I drafted a section in README (this PR) that explains it.

### CODE REVIEW

**Comment by bradgessler** [comment]
Does this apply to running Docker via `docker --platform=linux/amd64`? I'm running into issues with pressing x86 docker images from https://github.com/tamatebako/tebako-ci-containers on my M2 workstation.

**Comment by maxirmx** [comment]
> Does this apply to running Docker via `docker --platform=linux/amd64`? I'm running into issues with pressing x86 docker images from https://github.com/tamatebako/tebako-ci-containers on my M2 workstation.

If you see the error message as described here https://github.com/jemalloc/jemalloc/issues/1997  it is the case.

**Comment by bradgessler** [comment]
I ran into those errors and couldn't figure out a great solution for a CI build matrix via Github Actions, so I dusted off an old Intel Mac, installed docker on it, and am going to see if I can get macOS & Ubuntu building on amd64 and arm64 architecture.

**Comment by bradgessler** [comment]
The Dockerfile I'm working with is at https://github.com/bradgessler/tebako-ci-containers/blob/macos-qemu/ubuntu-20.04.Dockerfile

Running into issues like this:

```
Setting up tebako packaging environment
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
Tebako script failed: 'tebako setup' configure step failed [101]
The command '/bin/sh -c gem install tebako -v 0.12.2.rc1 &&     tebako setup -R ${ruby_version}' returned a non-zero code: 101
rake aborted!
Command failed with status (101): [docker build https://github.com/bradgessler/tebako-ci-containers.git#macos-qemu   -f ubuntu-20.04.Dockerfile   -t terminalwire_ubuntu_arm64
]
/Users/bradgessler/Projects/terminalwire/ruby/Rakefile:85:in 'block (3 levels) in <top (required)>'
Tasks: TOP => tebako:ubuntu => tebako:ubuntu:build => tebako:ubuntu:prepare
(See full trace by running task with —trace)
```

But I'll eventually make it through it.

**Comment by bradgessler** [comment]
Yay I figured out how to compile arm Linux on arm macOS—ARCH was hard coded to x86. I've removed that and have an ubuntu arm64 image building on macOS arm64.

https://github.com/bradgessler/tebako-ci-containers/commit/eb8d756a336f34d3d277cb4deaba4cf28f30690b

I'll open a PR on the CI image repo and reference this so discussion can continue.

For those watching, note that this doesn't solve this particular issue. In my approach I have both an Intel and M2 machine compiling Linux artifacts through docker in their respective architectures (no qemu).

**Pull request merged**
